version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu2004
for:
  - matrix:
      only:
        - image: Visual Studio 2019
    build:
      project: C#\LeetCode.sln
      verbosity: minimal
  - matrix:
      only:
        - image: Ubuntu2004
    build: off
    stack: go 1.15.6
    before_test:
      - go vet ./Go/...
    test_script:
      - go test -v ./Go/... 2>&1 | tee results.txt
    on_finish:
      - go get -u github.com/jstemmer/go-junit-report
      - cat results.txt | go-junit-report > report.xml
      - curl -F 'file=@report.xml' "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"
