version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu2004
for:
  - matrix:
      only:
        - image: Visual Studio 2019
    build:
      project: C#\LeetCode.sln
      verbosity: minimal
  - matrix:
      only:
        - image: Ubuntu2004
    build: off
    stack: go 1.15.6
    before_test:
      - go vet ./Go/...
      - go get -u github.com/jstemmer/go-junit-report
    test_script:
      - TTY=`tty` go test -v ./Go/... 2>&1 | tee ${TTY} | go-junit-report > report.xml
    on_finish:
      - curl -F 'file=@report.xml' "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"
